fn main() {
    println!("cargo:rerun-if-env-changed=TAURI_UPDATER_PUBLIC_KEY");
    println!("cargo:rerun-if-changed=tauri.conf.json");
    let public_key = std::env::var("TAURI_UPDATER_PUBLIC_KEY")
        .ok()
        .filter(|value| !value.trim().is_empty())
        .or_else(configured_updater_public_key);
    if let Some(public_key) = public_key {
        println!("cargo:rustc-env=TAURI_UPDATER_PUBLIC_KEY={public_key}");
    }

    let notice_path = std::path::Path::new("resources/licenses/THIRD_PARTY_NOTICES.txt");
    if let Some(parent) = notice_path.parent() {
        std::fs::create_dir_all(parent).expect("failed to create license resource directory");
    }
    if !notice_path.exists() {
        std::fs::write(
            notice_path,
            "Third-party notices are generated by npm run build.\n",
        )
        .expect("failed to create placeholder third-party notice file");
    }
    tauri_build::build();
}

/// Falls back to the updater public key committed in tauri.conf.json so builds
/// that do not export TAURI_UPDATER_PUBLIC_KEY can still verify updates.
fn configured_updater_public_key() -> Option<String> {
    let config = std::fs::read_to_string("tauri.conf.json").ok()?;
    let config: serde_json::Value = serde_json::from_str(&config).ok()?;
    config
        .pointer("/plugins/updater/pubkey")
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}
