use super::*;

/// Both live warnings and retrospective row badges use this local-only host matcher.
pub(super) fn url_match(state: &State, raw: &str) -> Option<(String, bool)> {
    let settings = &state.settings;
    if !settings.enabled || !settings.url_warnings {
        return None;
    }
    let local = suspicious_url(
        raw,
        &settings.blocked_domains,
        &settings.allowed_domains,
        false,
    );
    let remote = settings
        .sources
        .iter()
        .filter(|s| s.enabled && s.warn && s.format == SourceFormat::Domains)
        .find_map(|source| {
            let cache = state.caches.iter().find(|c| cache_matches(c, source))?;
            let parsed = url::Url::parse(raw.trim()).ok()?;
            if !matches!(parsed.scheme(), "https" | "http") {
                return None;
            }
            let host = parsed
                .host_str()?
                .trim_end_matches('.')
                .to_ascii_lowercase();
            if settings
                .allowed_domains
                .iter()
                .any(|d| domain_matches(&host, d))
            {
                return None;
            }
            cache
                .entries
                .iter()
                .any(|d| domain_matches(&host, d))
                .then_some((host, false))
        });
    local.or(remote).or_else(|| {
        suspicious_url(
            raw,
            &[],
            &settings.allowed_domains,
            settings.warn_shorteners,
        )
    })
}

impl SafetyRuntime {
    /// Read-only: no live jobs, notifications or moderation are generated by browsing history.
    pub fn inspect_rows(&self, rows: Vec<SafetyLogRow>) -> Result<Vec<Vec<String>>, String> {
        if rows.len() > 200
            || rows.iter().any(|r| {
                r.url.len() > 8192
                    || r.data.len() > 16384
                    || r.kind.len() > 40
                    || r.location.len() > 2048
                    || r.user_id.len() > 80
                    || r.created_at.len() > 80
                    || r.account_user_id.len() > 80
            })
        {
            return Err("Safety row inspection exceeds its limits".into());
        }
        let scope = self.auth.snapshot();
        let state = self.state.lock().unwrap();
        Ok(rows
            .iter()
            .map(|row| {
                if !scope.active
                    || !state.settings.enabled
                    || row.account_user_id != scope.current_user_id
                {
                    return Vec::new();
                }
                let mut warnings = BTreeSet::new();
                if matches!(
                    row.kind.as_str(),
                    "VideoPlay" | "StringLoad" | "ImageLoad" | "Event"
                ) {
                    let mut urls = if row.url.is_empty() {
                        Vec::new()
                    } else {
                        vec![row.url.clone()]
                    };
                    if row.kind == "Event"
                        && (row.data.starts_with("VideoURL:")
                            || row.data.starts_with("VideoError:")
                            || row.data.starts_with("VideoPlay("))
                    {
                        urls.extend(logged_urls(&row.data));
                    }
                    for url in urls {
                        if let Some((host, shortener)) = url_match(&state, &url) {
                            warnings.insert(if shortener {
                                format!(
                                    "URL shortener {host}: destination unknown; URL not opened."
                                )
                            } else {
                                format!("Potential IP-logger host {host}; URL not opened.")
                            });
                        }
                    }
                }
                if row.kind == "OnPlayerJoined" && valid_id(&row.user_id, "usr_") {
                    for source in state
                        .settings
                        .sources
                        .iter()
                        .filter(|s| s.enabled && s.warn && s.format == SourceFormat::UserIds)
                    {
                        if state
                            .caches
                            .iter()
                            .any(|c| cache_matches(c, source) && c.entries.contains(&row.user_id))
                        {
                            warnings.insert(format!(
                                "Currently listed by {} (community claim; verify before acting).",
                                source.name
                            ));
                        }
                    }
                }
                for entry in &state.audit {
                    if entry.action == "warn"
                        && entry.event_type != "SafetyUrl"
                        && !entry.event_created_at.is_empty()
                        && entry.account_user_id == row.account_user_id
                        && entry.event_created_at == row.created_at
                        && entry.user_id == row.user_id
                        && entry.log_kind == row.kind
                        && !row.location.is_empty()
                        && entry.location == row.location
                    {
                        warnings.insert(format!("Recorded warning: {}", entry.message));
                    }
                }
                warnings.into_iter().collect()
            })
            .collect())
    }
}
