[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=x86-64-v2", "--cfg", "reqwest_unstable"]

[target.'cfg(not(target_arch = "x86_64"))']
rustflags = ["--cfg", "reqwest_unstable"]

[target.'cfg(all(windows, target_env = "msvc"))']
linker = "lld-link.exe"
