import type { EntityRecord, EntityTimestamp } from './shared';

export type UserBadgeRecord = EntityRecord & {
    assignedAt?: string;
    badgeDescription?: string;
    badgeId?: string;
    badgeImageUrl?: string;
    badgeName?: string;
    hidden?: boolean;
    showcased?: boolean;
    updatedAt?: string;
};

type UserTravelingLocation = EntityRecord & {
    accessType?: string;
    accessTypeName?: string;
    ageGate?: boolean;
    canRequestInvite?: boolean;
    friendsId?: string | null;
    groupAccessType?: string | null;
    groupId?: string | null;
    hiddenId?: string | null;
    instanceId?: string;
    instanceName?: string;
    isOffline?: boolean;
    isPrivate?: boolean;
    isRealInstance?: boolean;
    isTraveling?: boolean;
    location?: string;
    privateId?: string | null;
    region?: string;
    shortName?: string;
    strict?: boolean;
    tag?: string;
    userId?: string | null;
    worldId?: string;
};

type UserPlatformHistoryRecord = EntityRecord & {
    isMobile: boolean;
    platform: string;
    recorded: string;
};

type UserPastDisplayNameRecord = EntityRecord & {
    displayName: string;
    updated_at: string;
};

export type UserProfileEntity = EntityRecord & {
    id?: string;
    displayName?: string;
    username?: string;
    name?: string;
    ageVerificationStatus?: string;
    ageVerified?: boolean;
    allowAvatarCopying?: boolean;
    acceptedPrivacyVersion?: number;
    acceptedTOSVersion?: number;
    accountDeletionDate?: string | null;
    accountDeletionLog?: string | null;
    appleDetails?: EntityRecord;
    appleId?: string;
    backgroundGradientBottom?: string;
    backgroundGradientTop?: string;
    backgroundTemplateId?: string;
    backgroundTextureId?: string;
    backgroundType?: string;
    badges?: UserBadgeRecord[];
    bannerColor?: string;
    bannerCustomUrl?: string;
    bannerType?: string;
    bannerUrl?: string;
    bio?: string;
    bioLinks?: string[];
    currentAvatar?: string;
    currentAvatarAuthorId?: string;
    currentAvatarImageUrl?: string;
    currentAvatarName?: string;
    currentAvatarTags?: string[];
    currentAvatarThumbnailImageUrl?: string;
    completedTutorials?: string[];
    contentFilters?: string[];
    date_joined?: string;
    developerType?: string;
    discordId?: string;
    discordDetails?: EntityRecord & { global_name?: string; id?: string };
    emailVerified?: boolean;
    fallbackAvatar?: string;
    friendKey?: string;
    friendGroupNames?: string[];
    friendRequestStatus?: string;
    friends?: string[];
    googleDetails?: EntityRecord;
    googleId?: string;
    hasAcceptedDiscordSocialSDKPerms?: boolean;
    hasBirthday?: boolean;
    hasDiscordFriendsOptOut?: boolean;
    hasEmail?: boolean;
    hasLoggedInFromClient?: boolean;
    hasPendingEmail?: boolean;
    hasSharedConnectionsOptOut?: boolean;
    hasVrcPlus?: boolean;
    hideContentFilterSettings?: boolean;
    homeLocation?: string;
    iconFrame?: string;
    iconType?: string;
    iconUrl?: string;
    imageUrl?: string;
    instanceId?: string;
    isAdult?: boolean;
    isBoopingEnabled?: boolean;
    isEconomyCreator?: boolean;
    isFriend?: boolean;
    isTemporary?: boolean;
    last_activity?: EntityTimestamp;
    last_login?: EntityTimestamp;
    last_mobile?: EntityTimestamp;
    last_platform?: string;
    location?: string;
    nameplateEffect?: string;
    note?: string;
    obfuscatedEmail?: string;
    obfuscatedPendingEmail?: string;
    oculusId?: string;
    pastDisplayNames?: UserPastDisplayNameRecord[];
    picoId?: string;
    platform?: string;
    platform_history?: UserPlatformHistoryRecord[];
    profileEffect?: string;
    pronouns?: string;
    pronounsHistory?: string[];
    queuedInstance?: string | null;
    receiveMobileInvitations?: boolean;
    state?: string;
    status?: string;
    statusDescription?: string;
    statusFirstTime?: boolean;
    statusHistory?: string[];
    steamDetails?: EntityRecord;
    steamId?: string;
    tags?: string[];
    travelingToInstance?: string;
    travelingToLocation?: string;
    travelingToWorld?: string;
    themeId?: string;
    themes?: unknown[];
    trustLevel?: string;
    temporaryExpiryDate?: string | null;
    twoFactorAuthEnabled?: boolean;
    twoFactorAuthEnabledDate?: string | null;
    unsubscribe?: boolean;
    userIcon?: string;
    updated_at?: string;
    userLanguage?: string | null;
    userLanguageCode?: string;
    usesGeneratedPassword?: boolean;
    viveId?: string;
    worldId?: string;
    $customTag?: string;
    $customTagColour?: string;
    $friendNumber?: number;
    $isModerator?: boolean;
    $isProbableTroll?: boolean;
    $isTroll?: boolean;
    $isVRCPlus?: boolean;
    $languages?: string[];
    $moderations?: EntityRecord;
    $platform?: string;
    $previousLocation?: string;
    $profileSource?: string;
    $travelingToLocation?: UserTravelingLocation;
    $trustClass?: string;
    $trustLevel?: string;
    $trustSortNum?: number;
    $userColour?: string;
};

export type UserProfileRecord = UserProfileEntity & {
    $trustLevel: string;
    $trustClass: string;
    $trustSortNum: number;
    $isModerator: boolean;
    $isTroll: boolean;
    $isProbableTroll: boolean;
    $platform: string;
};
